services:
  # Database Service
  mongodb:
    image: mongo:latest
    container_name: collegesphere_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # Backend Service
  backend:
    build: ./backend
    container_name: collegesphere_api
    restart: always
    ports:
      - "5002:5002"
    env_file:
      - .env
    depends_on:
      - mongodb

  # Frontend Service
  frontend:
    build:
      context: ./frontend
    container_name: collegesphere_web
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

# Persistent storage for MongoDB
volumes:
  mongo-data:
